{% set name = "radical.pilot" %}
{% set version = "0.90.6" %}
{% set sha256 = "bcbc3ab2122dea0700dba171f4d6c5ae1854169751b9918fd72fa8779703a38c" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: True  # [py3k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - radical.saga >=0.60
    - pymongo
    - radical.utils >=0.60
    - msgpack-python
    - pyzmq
    - python-hostlist
    - ntplib
    - netifaces
    - setproctitle
    
test:
  imports:
    - radical.pilot
  
about:
  home: http://radical-cybertools.github.io/radical-pilot/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'RADICAL-Pilot (RP) is a Pilot Job system written in Python'
  description: |
    RADICAL-Pilot is a flexible Pilot System that provides a simple and scalable 
    approach for executing many concurrent simulations and their data requirements 
    on clusters, grids, and clouds. RADICAL-Pilot is written in Python, and as such 
    is easily deployable into user space. It allows user-level control of Pilots 
    and supports a wide range of application types.
  dev_url: https://github.com/radical-cybertools/radical.pilot

extra:
  recipe-maintainers:
    - andre-merzky
    - iparask
